flags:
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- HDBC-2.4.0.1
- HDBC-sqlite3-2.3.3.1
- MonadRandom-0.4.2.3
- aeson-0.11.2.0
- base-compat-0.9.1
- bytestring-conversion-0.3.1
- connection-0.2.5
- convertible-1.1.1.0
- cookie-0.4.2
- directory-1.2.6.3
- double-conversion-2.0.1.0
- either-4.4.1.1
- fail-4.9.0.0
- http-api-data-0.2.3
- http-client-0.4.28
- http-client-tls-0.2.4
- http-media-0.6.3
- network-2.6.2.1
- process-1.4.2.0
- random-1.1
- regex-compat-0.95.1
- regex-posix-0.95.2
- servant-0.7.1
- servant-client-0.7.1
- socks-0.5.5
- streaming-commons-0.1.15.5
- string-conversions-0.4
- telegram-api-0.4.3.0
- time-1.5.0.1
- time-locale-compat-0.1.1.2
- tls-1.3.8
- unix-2.7.2.0
- utf8-string-1.0.1.1
- vault-0.3.0.6
- x509-system-1.6.3
resolver: ghc-8.0.1
