flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- RefSerialize-0.4.0
- TCache-0.12.1
- connection-0.2.5
- cookie-0.4.2
- http-client-0.4.28
- http-client-tls-0.2.4
- http-media-0.6.3
- servant-0.9.1.1
- servant-client-0.9.1.1
- streaming-commons-0.1.15.5
- string-conversions-0.4
- telegram-api-0.5.1.1
resolver: ghc-8.0.1
